version: '3'

volumes:
  elastic_data_becoming:
    driver: local
  
networks:
  becomingnet:
    external: true

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch-becoming
    environment:
      - cluster.name=es-becoming-cluster
      - cluster.initial_master_nodes=becoming01
      - node.name=becoming01
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data_becoming:/usr/share/elasticsearch/data
    networks:
      - becomingnet

  kibana:
    container_name: kibana-becoming
    image: docker.elastic.co/kibana/kibana:7.13.0
    environment:
      - server.name="becoming-kibana"
      - server.port=127.0.0.1:5601
      - elasticsearch.url="http://elasticsearch:9200"
    networks:
      - becomingnet
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:7.13.0
    container_name: apm-becoming
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - apm-server.secret_token=${APM_TOKEN}
    networks:
      - becomingnet
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.0
    ports:
      - "12201:12201/udp"
      - "5044:5044"
    environment:
      - "xpack.monitoring.elasticsearch.url=http://elasticsearch:9200"
    volumes:
      - .:/usr/share/logstash/pipeline
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - becomingnet
    command: logstash -f /usr/share/logstash/pipeline/ --config.reload.automatic
