version: '3'

networks:
  becomingnet:
    external: true

services:
  nginx:
    image: library/nginx:1.19.8-alpine
    container_name: nginx-becoming
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mysql-stream.conf:/etc/nginx/mysql-stream.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./404.html:/usr/share/nginx/html/404.html
      - ./htpasswd.nginx:/etc/apache2/.htpasswd
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - becomingnet

  certbot:
    image: certbot/certbot
    container_name: certbot-becoming
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami-becoming
    networks:
      - becomingnet
